// <auto-generated />
using System;
using EcoBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBilling.Infrastructure.Migrations
{
    [DbContext(typeof(EcoBillingDbContext))]
    [Migration("20260924115426_InitialIdentityPersistence")]
    partial class InitialIdentityPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.ToTable("user_accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_login_type", "login_type IN (1, 2)");

                            t.HasCheckConstraint("ck_user_accounts_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.OwnsOne("EcoBilling.Modules.Identity.Domain.LoginIdentity", "LoginIdentity", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_login");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("login_type");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Type", "NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ux_user_accounts_login_type_normalized_login");

                            b1.ToTable("user_accounts", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("LoginIdentity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
