// <auto-generated />
using System;
using EcoBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBilling.Infrastructure.Migrations
{
    [DbContext(typeof(EcoBillingDbContext))]
    [Migration("20260925164953_AddPayments")]
    partial class AddPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_accounts_address_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_account_number");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_accounts_resident_id");

                    b.ToTable("accounts", "accounts");
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apartment")
                        .HasColumnType("text")
                        .HasColumnName("apartment");

                    b.Property<string>("Building")
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_addresses_search_text");

                    b.ToTable("addresses", "accounts");
                });

            modelBuilder.Entity("EcoBilling.Modules.Billing.Domain.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("TariffVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_version_id");

                    b.HasKey("Id")
                        .HasName("pk_charges");

                    b.HasIndex("TariffVersionId")
                        .HasDatabaseName("ix_charges_tariff_version_id");

                    b.HasIndex("AccountId", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ux_charges_account_id_period_start_period_end");

                    b.ToTable("charges", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_charges_billing_period", "period_end > period_start");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_controllers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_controllers_user_id");

                    b.ToTable("controllers", "controllers");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.ToTable("user_accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_login_type", "login_type IN (1, 2)");

                            t.HasCheckConstraint("ck_user_accounts_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Meters.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_meters_account_id");

                    b.ToTable("meters", "meters");
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_payments_account_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_idempotency_key");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Readings.Domain.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("MeterId", "MeasuredAt")
                        .HasDatabaseName("ix_meter_readings_meter_id_measured_at");

                    b.ToTable("meter_readings", "readings", t =>
                        {
                            t.HasCheckConstraint("ck_meter_readings_value_non_negative", "value >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_residents_user_id");

                    b.ToTable("residents", "residents");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.ToTable("tariffs", "tariffs");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.TariffVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_id");

                    b.HasKey("Id")
                        .HasName("pk_tariff_versions");

                    b.HasIndex("TariffId", "EffectiveFrom")
                        .HasDatabaseName("ix_tariff_versions_tariff_id_effective_from");

                    b.ToTable("tariff_versions", "tariffs", t =>
                        {
                            t.HasCheckConstraint("ck_tariff_versions_effective_period", "effective_to IS NULL OR effective_to > effective_from");

                            t.HasCheckConstraint("ck_tariff_versions_rate_non_negative", "rate >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_addresses_address_id");

                    b.HasOne("EcoBilling.Modules.Residents.Domain.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_residents_resident_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Billing.Domain.Charge", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_accounts_account_id");

                    b.HasOne("EcoBilling.Modules.Tariffs.Domain.TariffVersion", null)
                        .WithMany()
                        .HasForeignKey("TariffVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_tariff_versions_tariff_version_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Controllers.Domain.Controller", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controllers_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.OwnsOne("EcoBilling.Modules.Identity.Domain.LoginIdentity", "LoginIdentity", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_login");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("login_type");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Type", "NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ux_user_accounts_login_type_normalized_login");

                            b1.ToTable("user_accounts", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("LoginIdentity")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoBilling.Modules.Meters.Domain.Meter", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meters_accounts_account_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.Payment", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_accounts_account_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Readings.Domain.MeterReading", b =>
                {
                    b.HasOne("EcoBilling.Modules.Meters.Domain.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_meters_meter_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_residents_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.TariffVersion", b =>
                {
                    b.HasOne("EcoBilling.Modules.Tariffs.Domain.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_versions_tariffs_tariff_id");
                });
#pragma warning restore 612, 618
        }
    }
}
