// <auto-generated />
using System;
using EcoBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBilling.Infrastructure.Migrations
{
    [DbContext(typeof(EcoBillingDbContext))]
    [Migration("20260925065110_AddAddresses")]
    partial class AddAddresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_accounts_address_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_account_number");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_accounts_resident_id");

                    b.ToTable("accounts", "accounts");
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apartment")
                        .HasColumnType("text")
                        .HasColumnName("apartment");

                    b.Property<string>("Building")
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_addresses_search_text");

                    b.ToTable("addresses", "accounts");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_controllers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_controllers_user_id");

                    b.ToTable("controllers", "controllers");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.ToTable("user_accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_login_type", "login_type IN (1, 2)");

                            t.HasCheckConstraint("ck_user_accounts_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_residents_user_id");

                    b.ToTable("residents", "residents");
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_addresses_address_id");

                    b.HasOne("EcoBilling.Modules.Residents.Domain.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_residents_resident_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Controllers.Domain.Controller", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controllers_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.OwnsOne("EcoBilling.Modules.Identity.Domain.LoginIdentity", "LoginIdentity", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_login");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("login_type");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Type", "NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ux_user_accounts_login_type_normalized_login");

                            b1.ToTable("user_accounts", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("LoginIdentity")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_residents_user_accounts_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
