// <auto-generated />
using System;
using EcoBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoBilling.Infrastructure.Migrations
{
    [DbContext(typeof(EcoBillingDbContext))]
    [Migration("20260929083554_CompleteV1Backend")]
    partial class CompleteV1Backend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoBilling.Infrastructure.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterData")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<string>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id_created_at");

                    b.ToTable("audit_logs", "infrastructure");
                });

            modelBuilder.Entity("EcoBilling.Infrastructure.Authentication.InternalServiceTokenReplay", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<string>("TokenId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Issuer", "TokenId")
                        .HasName("pk_internal_service_token_replays");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_internal_service_token_replays_expires_at");

                    b.ToTable("internal_service_token_replays", "infrastructure");
                });

            modelBuilder.Entity("EcoBilling.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", "infrastructure", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_retry_count_non_negative", "retry_count >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Overpayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("overpayment");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_accounts_address_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_account_number");

                    b.HasIndex("ResidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_resident_id");

                    b.ToTable("accounts", "accounts", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_overpayment_non_negative", "overpayment >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apartment")
                        .HasColumnType("text")
                        .HasColumnName("apartment");

                    b.Property<string>("Building")
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_addresses_search_text");

                    b.ToTable("addresses", "accounts");
                });

            modelBuilder.Entity("EcoBilling.Modules.Billing.Domain.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("calculation_version");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("consumption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CurrentReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_reading_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid?>("PreviousReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_reading_id");

                    b.Property<Guid>("TariffVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_version_id");

                    b.HasKey("Id")
                        .HasName("pk_charges");

                    b.HasIndex("CurrentReadingId")
                        .HasDatabaseName("ix_charges_current_reading_id");

                    b.HasIndex("PreviousReadingId")
                        .HasDatabaseName("ix_charges_previous_reading_id");

                    b.HasIndex("TariffVersionId")
                        .HasDatabaseName("ix_charges_tariff_version_id");

                    b.HasIndex("AccountId", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ux_charges_account_id_period_start_period_end");

                    b.ToTable("charges", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_charges_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_charges_billing_period", "period_end > period_start");

                            t.HasCheckConstraint("ck_charges_consumption_non_negative", "consumption >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_controllers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_controllers_user_id");

                    b.ToTable("controllers", "controllers");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.ControllerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_controller_assignments");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_controller_assignments_address_id");

                    b.HasIndex("ControllerId", "AddressId")
                        .IsUnique()
                        .HasDatabaseName("ux_controller_assignments_controller_id_address_id");

                    b.ToTable("controller_assignments", "controllers");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.ControllerCreationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_controller_creation_operations");

                    b.HasIndex("ControllerId")
                        .IsUnique()
                        .HasDatabaseName("ux_controller_creation_operations_controller_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_controller_creation_operations_idempotency_key");

                    b.ToTable("controller_creation_operations", "controllers");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.DirectorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("instance_slot");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_directors");

                    b.HasIndex("Slot")
                        .IsUnique()
                        .HasDatabaseName("ux_directors_instance_slot");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_directors_user_id");

                    b.ToTable("directors", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_directors_instance_slot", "instance_slot = 1");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.DirectorProvisioningOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("director_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_director_provisioning_operations");

                    b.HasIndex("DirectorId")
                        .HasDatabaseName("ix_director_provisioning_operations_director_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_director_provisioning_operations_idempotency_key");

                    b.ToTable("director_provisioning_operations", "identity");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("ReplacedBySessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_replaced_by_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_sessions_user_id");

                    b.ToTable("refresh_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_sessions_token_hash", "token_hash ~ '^[0-9A-F]{64}$'");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_password_change");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasDatabaseName("ux_user_accounts_single_director")
                        .HasFilter("\"role\" = 3");

                    b.ToTable("user_accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_failed_login_attempts", "failed_login_attempts >= 0");

                            t.HasCheckConstraint("ck_user_accounts_login_type", "login_type IN (1, 2)");

                            t.HasCheckConstraint("ck_user_accounts_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Meters.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ReplacesMeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaces_meter_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_meters_account_id");

                    b.HasIndex("ReplacesMeterId")
                        .IsUnique()
                        .HasDatabaseName("ux_meters_replaces_meter_id")
                        .HasFilter("replaces_meter_id IS NOT NULL");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_meters_serial_number");

                    b.ToTable("meters", "meters");
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_payments_account_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_idempotency_key");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_allocations");

                    b.HasIndex("ChargeId")
                        .HasDatabaseName("ix_payment_allocations_charge_id");

                    b.HasIndex("PaymentId", "ChargeId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_allocations_payment_id_charge_id");

                    b.ToTable("payment_allocations", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_allocations_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Readings.Domain.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correction_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid?>("SupersedesReadingId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_reading_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_meter_readings");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_meter_readings_author_user_id");

                    b.HasIndex("SupersedesReadingId")
                        .IsUnique()
                        .HasDatabaseName("ux_meter_readings_supersedes_reading_id")
                        .HasFilter("supersedes_reading_id IS NOT NULL");

                    b.HasIndex("MeterId", "MeasuredAt")
                        .HasDatabaseName("ix_meter_readings_meter_id_measured_at");

                    b.ToTable("meter_readings", "readings", t =>
                        {
                            t.HasCheckConstraint("ck_meter_readings_source", "source IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_meter_readings_value_non_negative", "value >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_residents_user_id");

                    b.ToTable("residents", "residents");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.ResidentCreationOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_resident_creation_operations");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_creation_operations_account_id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_creation_operations_address_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_creation_operations_idempotency_key");

                    b.HasIndex("ResidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_creation_operations_resident_id");

                    b.ToTable("resident_creation_operations", "residents");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.ResidentPasswordResetOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_resident_password_reset_operations");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_resident_password_reset_operations_idempotency_key");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_resident_password_reset_operations_resident_id");

                    b.ToTable("resident_password_reset_operations", "residents");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.AccountTariffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_id");

                    b.HasKey("Id")
                        .HasName("pk_account_tariff_assignments");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_account_tariff_assignments_tariff_id");

                    b.HasIndex("AccountId", "EffectiveFrom")
                        .HasDatabaseName("ix_account_tariff_assignments_account_id_effective_from");

                    b.ToTable("account_tariff_assignments", "tariffs", t =>
                        {
                            t.HasCheckConstraint("ck_account_tariff_assignments_effective_period", "effective_to IS NULL OR effective_to > effective_from");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tariffs_name");

                    b.ToTable("tariffs", "tariffs");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.TariffVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_id");

                    b.HasKey("Id")
                        .HasName("pk_tariff_versions");

                    b.HasIndex("TariffId", "EffectiveFrom")
                        .HasDatabaseName("ix_tariff_versions_tariff_id_effective_from");

                    b.ToTable("tariff_versions", "tariffs", t =>
                        {
                            t.HasCheckConstraint("ck_tariff_versions_effective_period", "effective_to IS NULL OR effective_to > effective_from");

                            t.HasCheckConstraint("ck_tariff_versions_rate_non_negative", "rate >= 0");
                        });
                });

            modelBuilder.Entity("EcoBilling.Modules.Accounts.Domain.Account", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_addresses_address_id");

                    b.HasOne("EcoBilling.Modules.Residents.Domain.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_residents_resident_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Billing.Domain.Charge", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_accounts_account_id");

                    b.HasOne("EcoBilling.Modules.Readings.Domain.MeterReading", null)
                        .WithMany()
                        .HasForeignKey("CurrentReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charges_readings_current_reading_id");

                    b.HasOne("EcoBilling.Modules.Readings.Domain.MeterReading", null)
                        .WithMany()
                        .HasForeignKey("PreviousReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_charges_readings_previous_reading_id");

                    b.HasOne("EcoBilling.Modules.Tariffs.Domain.TariffVersion", null)
                        .WithMany()
                        .HasForeignKey("TariffVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_tariff_versions_tariff_version_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.Controller", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Controllers.Domain.Controller", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controllers_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.ControllerAssignment", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Address", null)
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controller_assignments_addresses_address_id");

                    b.HasOne("EcoBilling.Modules.Controllers.Domain.Controller", null)
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controller_assignments_controllers_controller_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Controllers.Domain.ControllerCreationOperation", b =>
                {
                    b.HasOne("EcoBilling.Modules.Controllers.Domain.Controller", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Controllers.Domain.ControllerCreationOperation", "ControllerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_controller_creation_operations_controllers_controller_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.DirectorProfile", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Identity.Domain.DirectorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_directors_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.DirectorProvisioningOperation", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.DirectorProfile", null)
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_director_provisioning_operations_directors_director_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.RefreshSession", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.RefreshSession", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Identity.Domain.RefreshSession", "ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_sessions_replacement");

                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.OwnsOne("EcoBilling.Modules.Identity.Domain.LoginIdentity", "LoginIdentity", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_login");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("login_type");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex("Type", "NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ux_user_accounts_login_type_normalized_login");

                            b1.ToTable("user_accounts", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("LoginIdentity")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoBilling.Modules.Meters.Domain.Meter", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meters_accounts_account_id");

                    b.HasOne("EcoBilling.Modules.Meters.Domain.Meter", null)
                        .WithMany()
                        .HasForeignKey("ReplacesMeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meters_meters_replaces_meter_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.Payment", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_accounts_account_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Payments.Domain.PaymentAllocation", b =>
                {
                    b.HasOne("EcoBilling.Modules.Billing.Domain.Charge", null)
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_charges_charge_id");

                    b.HasOne("EcoBilling.Modules.Payments.Domain.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_payments_payment_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Readings.Domain.MeterReading", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meter_readings_user_accounts_author_user_id");

                    b.HasOne("EcoBilling.Modules.Meters.Domain.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_readings_meters_meter_id");

                    b.HasOne("EcoBilling.Modules.Readings.Domain.MeterReading", null)
                        .WithMany()
                        .HasForeignKey("SupersedesReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meter_readings_meter_readings_supersedes_reading_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.Resident", b =>
                {
                    b.HasOne("EcoBilling.Modules.Identity.Domain.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_residents_user_accounts_user_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.ResidentCreationOperation", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.ResidentCreationOperation", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_creation_operations_accounts_account_id");

                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Address", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.ResidentCreationOperation", "AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_creation_operations_addresses_address_id");

                    b.HasOne("EcoBilling.Modules.Residents.Domain.Resident", null)
                        .WithOne()
                        .HasForeignKey("EcoBilling.Modules.Residents.Domain.ResidentCreationOperation", "ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_creation_operations_residents_resident_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Residents.Domain.ResidentPasswordResetOperation", b =>
                {
                    b.HasOne("EcoBilling.Modules.Residents.Domain.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resident_password_reset_operations_residents_resident_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.AccountTariffAssignment", b =>
                {
                    b.HasOne("EcoBilling.Modules.Accounts.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_tariff_assignments_accounts_account_id");

                    b.HasOne("EcoBilling.Modules.Tariffs.Domain.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_tariff_assignments_tariffs_tariff_id");
                });

            modelBuilder.Entity("EcoBilling.Modules.Tariffs.Domain.TariffVersion", b =>
                {
                    b.HasOne("EcoBilling.Modules.Tariffs.Domain.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_versions_tariffs_tariff_id");
                });
#pragma warning restore 612, 618
        }
    }
}
