substitutions:
  _REGION: europe-west1
  _REPOSITORY: ecobilling
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/Dockerfile.api
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-api:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/Dockerfile.worker
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-worker:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/Dockerfile.api
      - --target
      - migrations
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-migrations:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-api:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-worker:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/ecobilling-migrations:${_TAG}
